[advisories]
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "AGPL-3.0-only",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
