package estimate

import (
	"encoding/json"
	"slices"
	"testing"

	"github.com/tyk-swe/olp/tests/fixtures"
)

// fixture is one oracle record: the token ids OpenAI's tiktoken produces for a
// text, generated by tests/fixtures/tokens/generate.py.
type fixture struct {
	Name     string   `json:"name"`
	Encoding string   `json:"encoding"`
	Text     string   `json:"text"`
	Tokens   []uint32 `json:"tokens"`
}

func loadFixtures(t testing.TB, file string) []fixture {
	t.Helper()
	data, err := fixtures.Files.ReadFile("tokens/" + file)
	if err != nil {
		t.Fatal(err)
	}
	var out []fixture
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatalf("%s: %v", file, err)
	}
	return out
}

func encodingNamed(t testing.TB, name string) *Encoding {
	t.Helper()
	for _, e := range []*Encoding{O200kBase, CL100kBase} {
		if e.Name() == name {
			return e
		}
	}
	t.Fatalf("no encoding named %q", name)
	return nil
}

// TestOracleFixtures holds both encodings to tiktoken's exact output: every
// token id, not only the count, on every fixture.
func TestOracleFixtures(t *testing.T) {
	for _, file := range []string{"o200k_base.json", "cl100k_base.json"} {
		fixtures := loadFixtures(t, file)
		if len(fixtures) < 400 {
			t.Fatalf("%s holds %d fixtures, want the full corpus", file, len(fixtures))
		}
		for _, f := range fixtures {
			t.Run(f.Encoding+"/"+f.Name, func(t *testing.T) {
				e := encodingNamed(t, f.Encoding)
				ids, err := e.Encode(f.Text)
				if err != nil {
					t.Fatal(err)
				}
				if !slices.Equal(ids, f.Tokens) {
					t.Fatalf("Encode differs from tiktoken: %s", firstDifference(ids, f.Tokens))
				}
				n, err := e.Count(f.Text)
				if err != nil {
					t.Fatal(err)
				}
				if n != len(f.Tokens) {
					t.Fatalf("Count = %d, tiktoken counts %d", n, len(f.Tokens))
				}
			})
		}
	}
}

func firstDifference(got, want []uint32) string {
	for i := range min(len(got), len(want)) {
		if got[i] != want[i] {
			return "token " + itoa(i) + " is " + itoa(int(got[i])) + ", want " + itoa(int(want[i])) + " (of " + itoa(len(got)) + " and " + itoa(len(want)) + ")"
		}
	}
	return "got " + itoa(len(got)) + " tokens, want " + itoa(len(want))
}

func itoa(n int) string {
	b, _ := json.Marshal(n)
	return string(b)
}
