package protocols

import (
	"bytes"
	"encoding/json"
	"errors"
	"strings"
	"testing"

	"github.com/tyk-swe/olp/internal/oif"
	"github.com/tyk-swe/olp/internal/protocols/openai"
	"github.com/tyk-swe/olp/internal/protocols/sse"
)

// The wire traces below are authored from the documented Anthropic Messages
// streaming grammar, not captured from or generated by the code under test.
func anthropicWireEvent(name, data string) string {
	return "event: " + name + "\ndata: " + data + "\n\n"
}

const (
	anthropicStartWire = `event: message_start
data: {"type":"message_start","message":{"id":"msg_1","type":"message","role":"assistant","model":"wire-model","content":[],"usage":{"input_tokens":3,"output_tokens":1}}}

`
	anthropicTextWire = `event: content_block_start
data: {"type":"content_block_start","index":0,"content_block":{"type":"text","text":""}}

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"hi"}}

event: content_block_stop
data: {"type":"content_block_stop","index":0}

`

	anthropicStopWire = `event: message_stop
data: {"type":"message_stop"}

`
)

// streamEventNames decodes emitted frames with an independent reader so the
// oracle does not share the production encoder.
func streamEventNames(t *testing.T, raw []byte) []string {
	t.Helper()
	var names []string
	for _, frame := range strings.Split(string(raw), "\n\n") {
		frame = strings.TrimSpace(frame)
		if frame == "" {
			continue
		}
		var name, data string
		for _, line := range strings.Split(frame, "\n") {
			if strings.HasPrefix(line, "event: ") {
				name = strings.TrimPrefix(line, "event: ")
			}
			if strings.HasPrefix(line, "data: ") {
				data = strings.TrimPrefix(line, "data: ")
			}
		}
		var payload map[string]json.RawMessage
		if err := json.Unmarshal([]byte(data), &payload); err != nil {
			t.Fatalf("emitted frame is not JSON: %q", frame)
		}
		var typ string
		if err := json.Unmarshal(payload["type"], &typ); err != nil {
			t.Fatalf("emitted frame has no string type: %q", frame)
		}
		if name == "" {
			name = typ
		}
		if name != typ {
			t.Fatalf("emitted frame name/type disagree: %q", frame)
		}
		names = append(names, name)
	}
	return names
}

func TestAnthropicTraceAdmitsLegalUpdateVariants(t *testing.T) {
	for _, tc := range []struct {
		name       string
		wire       string
		reason     string
		sequence   string
		hasReason  bool
		hasSeq     bool
		usage      string
		terminated bool
	}{
		{
			name: "single update positive control",
			wire: anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn","stop_sequence":null},"usage":{"output_tokens":7}}`) +
				anthropicStopWire,
			reason: "end_turn", hasReason: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":7}`,
		},
		{
			name: "usage updates before final reason",
			wire: anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":null,"stop_sequence":null},"usage":{"output_tokens":5}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":7}}`) +
				anthropicStopWire,
			reason: "end_turn", hasReason: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":7}`,
		},
		{
			name: "consistent updates after initial reason",
			wire: anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn","stop_sequence":null},"usage":{"output_tokens":7}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","usage":{"output_tokens":9}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"}}`) +
				anthropicStopWire,
			reason: "end_turn", hasReason: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":9}`,
		},
		{
			name: "omitted usage fields keep cumulative counts",
			wire: `event: message_start
data: {"type":"message_start","message":{"id":"msg_1","type":"message","role":"assistant","model":"wire-model","content":[],"usage":{"input_tokens":3,"output_tokens":1,"cache_read_input_tokens":2}}}

` + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{}}`) +
				anthropicStopWire,
			reason: "end_turn", hasReason: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":1,"cache_read_input_tokens":2}`,
		},
		{
			name: "absent delta member and null fields",
			wire: anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","usage":{"output_tokens":4}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":null}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"max_tokens"}}`) +
				anthropicStopWire,
			reason: "max_tokens", hasReason: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":4}`,
		},
		{
			name: "declared stop sequence survives updates",
			wire: anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"stop_sequence","stop_sequence":"###"},"usage":{"output_tokens":4}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"stop_sequence","stop_sequence":"###"}}`) +
				anthropicStopWire,
			reason: "stop_sequence", hasReason: true, sequence: "###", hasSeq: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":4}`,
		},
		{
			name: "message_stop is the terminal boundary without a reason",
			wire: anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("message_delta", `{"type":"message_delta","usage":{"output_tokens":4}}`) +
				anthropicStopWire,
			terminated: true,
			usage:      `{"input_tokens":3,"output_tokens":4}`,
		},
		{
			name: "pings and unknown extension events are admitted",
			wire: `event: ping
data: {"type":"ping"}

` + anthropicStartWire + anthropicTextWire +
				anthropicWireEvent("custom_extension", `{"type":"custom_extension","x":1}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":7}}`) +
				anthropicStopWire,
			reason: "end_turn", hasReason: true, terminated: true,
			usage: `{"input_tokens":3,"output_tokens":7}`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			trace := NewAnthropicTrace(1 << 20)
			var names []string
			seq := uint64(0)
			err := sse.Decode(strings.NewReader(tc.wire), 1<<20, func(frame sse.Frame) error {
				event, e := openai.LiftSSE(openai.FamilyAnthropic, frame, seq, 1<<20)
				if e != nil {
					return e
				}
				seq++
				tr, e := trace.Accept(event)
				if e != nil {
					return e
				}
				if tr.Effect == AnthropicForward {
					names = append(names, tr.Type)
				}
				return nil
			})
			if err != nil {
				t.Fatal(err)
			}
			if trace.Terminal() != tc.terminated {
				t.Fatalf("terminal=%v want %v", trace.Terminal(), tc.terminated)
			}
			if reason, ok := trace.StopReason(); ok != tc.hasReason || reason != tc.reason {
				t.Fatalf("stop reason %q,%v want %q,%v", reason, ok, tc.reason, tc.hasReason)
			}
			if seq, ok := trace.StopSequence(); ok != tc.hasSeq || seq != tc.sequence {
				t.Fatalf("stop sequence %q,%v want %q,%v", seq, ok, tc.sequence, tc.hasSeq)
			}
			usage, _ := json.Marshal(trace.Usage())
			var expected, got any
			if json.Unmarshal([]byte(tc.usage), &expected) != nil || json.Unmarshal(usage, &got) != nil {
				t.Fatalf("usage decode: %s", usage)
			}
			if !jsonEqual(expected, got) {
				t.Fatalf("cumulative usage %s want %s", usage, tc.usage)
			}
			// Forwarded events are exactly the admitted payload types minus
			// transport-only traffic.
			for _, n := range names {
				if n == "ping" || n == "error" {
					t.Fatalf("dropped effect leaked onto wire: %v", names)
				}
			}
		})
	}
}

func jsonEqual(a, b any) bool {
	x, _ := json.Marshal(a)
	y, _ := json.Marshal(b)
	return bytes.Equal(x, y)
}

func TestAnthropicStreamForwardsLegalMultiUpdateTraces(t *testing.T) {
	wire := anthropicStartWire + anthropicTextWire +
		anthropicWireEvent("ping", `{"type":"ping"}`) +
		anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":null,"stop_sequence":null},"usage":{"output_tokens":5}}`) +
		anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":7,"cache_read_input_tokens":2}}`) +
		anthropicStopWire
	var out bytes.Buffer
	c, err := Stream(openai.FamilyAnthropic, openai.FamilyAnthropic, strings.NewReader(wire), 1<<20, "route", true, func(frame []byte) error {
		out.Write(frame)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if c.FinishReason != "stop" || c.UpstreamID != "msg_1" || c.ProviderModel != "wire-model" {
		t.Fatalf("completion facts lost: %+v", c)
	}
	if c.Usage == nil || c.Usage.InputTokens != 5 || c.Usage.OutputTokens != 7 || c.Usage.TotalTokens != 12 {
		t.Fatalf("cumulative usage lost: %+v", c.Usage)
	}
	if c.Usage.CachedInputTokens == nil || *c.Usage.CachedInputTokens != 2 {
		t.Fatalf("cache read usage lost: %+v", c.Usage)
	}
	names := streamEventNames(t, out.Bytes())
	expected := []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop", "message_delta", "message_delta", "message_stop"}
	if strings.Join(names, ",") != strings.Join(expected, ",") {
		t.Fatalf("forwarded events %v want %v", names, expected)
	}
	if !strings.Contains(out.String(), `"model":"route"`) {
		t.Fatalf("route model binding was not rewritten on forward: %s", out.String())
	}
}

func TestAnthropicTracePreservesAdmittedFraming(t *testing.T) {
	wire := `id: evt-9
retry: 3000
event: message_start
data: {"type":"message_start","message":{"id":"msg_1","type":"message","role":"assistant","model":"wire-model","content":[],"usage":{"input_tokens":3,"output_tokens":1}}}

` + anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":2}}`) +
		anthropicStopWire
	var out bytes.Buffer
	_, err := Stream(openai.FamilyAnthropic, openai.FamilyAnthropic, strings.NewReader(wire), 1<<20, "route", true, func(frame []byte) error {
		out.Write(frame)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "id: evt-9\nretry: 3000\nevent: message_start") {
		t.Fatalf("admitted SSE framing was dropped on native forward: %q", out.String())
	}
}

func TestAnthropicTraceRejectsInvalidNeighbors(t *testing.T) {
	base := anthropicStartWire + anthropicTextWire
	finalDelta := anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":7}}`)
	for _, tc := range []struct {
		name    string
		wire    string
		emitted []string
	}{
		{
			name:    "duplicate message_start",
			wire:    anthropicStartWire + anthropicStartWire,
			emitted: []string{"message_start"},
		},
		{
			name: "event name disagrees with payload type",
			wire: base + `event: message_stop
data: {"type":"message_delta","delta":{"stop_reason":"end_turn"}}

`,
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop"},
		},
		{
			name: "missing event type",
			wire: base + `event: content_block_start
data: {"index":1,"content_block":{"type":"text","text":""}}

`,
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop"},
		},
		{
			name: "content before message_start",
			wire: anthropicWireEvent("content_block_start", `{"type":"content_block_start","index":0,"content_block":{"type":"text","text":""}}`),
		},
		{
			name:    "content_block_delta at invalid position",
			wire:    base + anthropicWireEvent("content_block_delta", `{"type":"content_block_delta","index":4,"delta":{"type":"text_delta","text":"x"}}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop"},
		},
		{
			name:    "content_block_start skips block index",
			wire:    anthropicStartWire + anthropicWireEvent("content_block_start", `{"type":"content_block_start","index":1,"content_block":{"type":"text","text":""}}`),
			emitted: []string{"message_start"},
		},
		{
			name:    "delta on a closed block",
			wire:    base + anthropicWireEvent("content_block_delta", `{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"x"}}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop"},
		},
		{
			name: "message_delta while a block is open",
			wire: anthropicStartWire +
				anthropicWireEvent("content_block_start", `{"type":"content_block_start","index":0,"content_block":{"type":"text","text":""}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"}}`),
			emitted: []string{"message_start", "content_block_start"},
		},
		{
			name: "content_block_start after the update phase began",
			wire: base +
				anthropicWireEvent("message_delta", `{"type":"message_delta","usage":{"output_tokens":4}}`) +
				anthropicWireEvent("content_block_start", `{"type":"content_block_start","index":1,"content_block":{"type":"text","text":""}}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop", "message_delta"},
		},
		{
			name: "contradictory stop reasons",
			wire: base + finalDelta +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"max_tokens"}}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop", "message_delta"},
		},
		{
			name: "contradictory stop sequences",
			wire: base +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"stop_sequence","stop_sequence":"###"}}`) +
				anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"stop_sequence","stop_sequence":"!!!"}}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop", "message_delta"},
		},
		{
			name:    "non-string stop reason",
			wire:    base + anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":42}}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop"},
		},
		{
			name:    "message_delta with non-object delta",
			wire:    base + anthropicWireEvent("message_delta", `{"type":"message_delta","delta":"end_turn"}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop"},
		},
		{
			name: "text delta on a tool block",
			wire: anthropicStartWire +
				anthropicWireEvent("content_block_start", `{"type":"content_block_start","index":0,"content_block":{"type":"tool_use","id":"call_1","name":"weather","input":{}}}`) +
				anthropicWireEvent("content_block_delta", `{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"x"}}`),
			emitted: []string{"message_start", "content_block_start"},
		},
		{
			name: "unparseable tool arguments at block stop",
			wire: anthropicStartWire +
				anthropicWireEvent("content_block_start", `{"type":"content_block_start","index":0,"content_block":{"type":"tool_use","id":"call_1","name":"weather","input":{}}}`) +
				anthropicWireEvent("content_block_delta", `{"type":"content_block_delta","index":0,"delta":{"type":"input_json_delta","partial_json":"{bad"}}`) +
				anthropicWireEvent("content_block_stop", `{"type":"content_block_stop","index":0}`),
			emitted: []string{"message_start", "content_block_start", "content_block_delta"},
		},
		{
			name:    "non-integer index",
			wire:    anthropicStartWire + anthropicWireEvent("content_block_delta", `{"type":"content_block_delta","index":1.5,"delta":{"type":"text_delta","text":"x"}}`),
			emitted: []string{"message_start"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var out bytes.Buffer
			_, err := Stream(openai.FamilyAnthropic, openai.FamilyAnthropic, strings.NewReader(tc.wire), 1<<20, "route", true, func(frame []byte) error {
				out.Write(frame)
				return nil
			})
			if err == nil {
				t.Fatalf("invalid neighbor admitted: %s", out.String())
			}
			// Partial delivery is reported honestly: exactly the admitted
			// prefix was forwarded, never the violating event or a
			// manufactured terminal.
			names := streamEventNames(t, out.Bytes())
			if strings.Join(names, ",") != strings.Join(tc.emitted, ",") {
				t.Fatalf("delivered prefix %v want %v", names, tc.emitted)
			}
		})
	}
}

func TestAnthropicTraceRejectsMalformedUsage(t *testing.T) {
	base := anthropicStartWire + anthropicTextWire
	for _, tc := range []struct{ name, usage string }{
		{"string count", `{"output_tokens":"many"}`},
		{"negative count", `{"output_tokens":-1}`},
		{"non-integer count", `{"output_tokens":1.5}`},
		{"null count", `{"output_tokens":null}`},
		{"non-object usage", `[7]`},
		{"cache detail exceeds total", `{"output_tokens":4,"cache_creation_input_tokens":2,"cache_creation":{"ephemeral_5m_input_tokens":9}}`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			wire := base + anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":`+tc.usage+`}`) + anthropicStopWire
			_, err := Stream(openai.FamilyAnthropic, openai.FamilyAnthropic, strings.NewReader(wire), 1<<20, "route", true, func([]byte) error { return nil })
			if err == nil {
				t.Fatal("malformed usage admitted")
			}
		})
	}
}

func TestAnthropicTraceTerminalBoundary(t *testing.T) {
	wire := anthropicStartWire + anthropicTextWire +
		anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":7}}`) +
		anthropicStopWire
	events := []oif.Event{}
	seq := uint64(0)
	if err := sse.Decode(strings.NewReader(wire), 1<<20, func(frame sse.Frame) error {
		event, e := openai.LiftSSE(openai.FamilyAnthropic, frame, seq, 1<<20)
		if e != nil {
			return e
		}
		seq++
		events = append(events, event)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	trace := NewAnthropicTrace(1 << 20)
	for _, event := range events {
		if _, err := trace.Accept(event); err != nil {
			t.Fatal(err)
		}
	}
	if !trace.Terminal() {
		t.Fatal("message_stop did not close the trace")
	}
	// Cleanup must not manufacture another outcome: any later event is a
	// protocol violation, not a second terminal.
	trailing, e := openai.LiftSSE(openai.FamilyAnthropic, sse.Frame{Event: ptr("message_delta"), Data: `{"type":"message_delta","delta":{"stop_reason":"max_tokens"}}`}, seq, 1<<20)
	if e != nil {
		t.Fatal(e)
	}
	if _, err := trace.Accept(trailing); err == nil {
		t.Fatal("event after message_stop admitted")
	}
}

func TestAnthropicStreamTruncationIsHonest(t *testing.T) {
	wire := anthropicStartWire + anthropicTextWire +
		anthropicWireEvent("message_delta", `{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":7}}`)
	var out bytes.Buffer
	_, err := Stream(openai.FamilyAnthropic, openai.FamilyAnthropic, strings.NewReader(wire), 1<<20, "route", true, func(frame []byte) error {
		out.Write(frame)
		return nil
	})
	var pe *openai.ProtocolError
	if !errors.As(err, &pe) || !pe.Truncated {
		t.Fatalf("EOF before message_stop is not a truncated protocol error: %v", err)
	}
	names := streamEventNames(t, out.Bytes())
	expected := []string{"message_start", "content_block_start", "content_block_delta", "content_block_stop", "message_delta"}
	if strings.Join(names, ",") != strings.Join(expected, ",") {
		t.Fatalf("delivered prefix %v want %v", names, expected)
	}
}

func ptr[T any](v T) *T { return &v }
