//! Generator for the surface × operation × provider-kind table in
//! `docs/compatibility.md`.
//!
//! The rows come from the endpoint registry and the cells from
//! [`certification::supports`], which is what actually gates activation, so
//! the published table cannot claim a tuple the gateway would refuse.
//! `cargo run -p olp --example export_compatibility` prints [`markdown`];
//! `make compat` splices it between the markers and the
//! `compatibility_drift` integration test fails when the copy is stale.

use olp_engine::domain::canonical::identity::{OperationKind, Surface, TransportMode};
use olp_engine::domain::routing::provider::ProviderKind;
use olp_engine::providers::factory::certification;

use super::endpoint_policy::export::{RegisteredOperation, registered_operations};

pub const START_MARKER: &str = "<!-- generated:compatibility:start -->";
pub const END_MARKER: &str = "<!-- generated:compatibility:end -->";

/// Documented surfaces, in the order the table presents them, with the
/// spelling used in prose.
const SURFACES: [(Surface, &str); 3] = [
    (Surface::OpenAi, "OpenAI"),
    (Surface::Anthropic, "Anthropic"),
    (Surface::Gemini, "Gemini"),
];

const GENERATED_NOTICE: &str = "\
<!--
Generated by `make compat`
(cargo run --locked -p olp --example export_compatibility) from
apps/olp/src/gateway/endpoint_policy/registry.rs and
crates/olp-engine/src/providers/factory/certification.rs.
Do not edit between the markers.
-->";

/// Renders the generated section of `docs/compatibility.md`, markers
/// included, ending with a newline.
#[must_use]
pub fn markdown() -> String {
    let operations = registered_operations();
    let mut rendered = format!("{START_MARKER}\n{GENERATED_NOTICE}\n");
    for (surface, name) in SURFACES {
        rendered.push_str(&surface_section(surface, name, &operations));
    }
    rendered.push_str(&format!("\n{END_MARKER}\n"));
    rendered
}

fn surface_section(surface: Surface, name: &str, operations: &[RegisteredOperation]) -> String {
    let rows: Vec<&RegisteredOperation> = operations
        .iter()
        .filter(|operation| operation.surface == surface)
        .collect();
    assert!(!rows.is_empty(), "{name} surface has no registered routes");
    let mut section = format!("\n### {name} surface\n\n");
    if let Some(note) = surface_note(surface, &rows) {
        section.push_str(&note);
        section.push_str("\n\n");
    }
    section.push_str(&table(surface, &rows));
    section
}

/// The alias and version notes are claims about the registry, so they are
/// asserted against it rather than written by hand.
fn surface_note(surface: Surface, rows: &[&RegisteredOperation]) -> Option<String> {
    match surface {
        Surface::OpenAi => {
            for row in rows {
                let bare = row
                    .path
                    .strip_prefix("/openai")
                    .expect("an OpenAI-surface route is served under /openai");
                assert_eq!(
                    row.aliases
                        .iter()
                        .map(|alias| placeholders(alias))
                        .collect::<Vec<_>>(),
                    vec![placeholders(bare)],
                    "{} {} must alias the bare /v1 path",
                    row.method,
                    row.path
                );
            }
            Some(
                "Every `/openai/v1` route is also served at the bare `/v1`\nalias, \
                 so an OpenAI SDK pointed at a base URL ending in `/v1`\nworks \
                 unchanged."
                    .to_owned(),
            )
        }
        Surface::Anthropic => None,
        Surface::Gemini => {
            let stable = version_paths(rows, "/gemini/v1/");
            let beta = version_paths(rows, "/gemini/v1beta/");
            assert!(!stable.is_empty(), "the Gemini v1 routes are missing");
            assert_eq!(stable, beta, "the Gemini API versions must agree");
            Some(
                "Every Gemini route is served under both `/gemini/v1` and\n\
                 `/gemini/v1beta`; the table lists each version because a client\n\
                 picks one in its base URL."
                    .to_owned(),
            )
        }
    }
}

fn version_paths(rows: &[&RegisteredOperation], prefix: &str) -> Vec<String> {
    rows.iter()
        .filter_map(|row| row.path.strip_prefix(prefix))
        .map(|suffix| suffix.to_owned())
        .collect()
}

/// Collapses `{video_id}` and `{model_id}` to `{}` so an alias that names its
/// path parameter differently still compares equal to the canonical route.
fn placeholders(path: &str) -> String {
    let mut normalized = String::new();
    let mut rest = path;
    while let Some((before, after)) = rest.split_once('{') {
        let (_, after) = after
            .split_once('}')
            .expect("a route path placeholder is closed");
        normalized.push_str(before);
        normalized.push_str("{}");
        rest = after;
    }
    normalized.push_str(rest);
    normalized
}

fn table(surface: Surface, rows: &[&RegisteredOperation]) -> String {
    let mut table = String::from("| Endpoint | Operation |");
    for kind in ProviderKind::ALL {
        table.push_str(&format!(" {} |", kind.as_str()));
    }
    table.push_str("\n|---|---|");
    table.push_str(&"---|".repeat(ProviderKind::ALL.len()));
    table.push('\n');
    for row in rows {
        table.push_str(&format!(
            "| `{} {}` | {} |",
            row.method,
            row.path,
            row.operation.as_str()
        ));
        for kind in ProviderKind::ALL {
            table.push_str(&format!(" {} |", cell(kind, row.operation, surface)));
        }
        table.push('\n');
    }
    table
}

/// A tuple is documented as reachable only when the connector has a
/// certification path for it in some transport mode, because activation
/// refuses everything else.
fn cell(kind: ProviderKind, operation: OperationKind, surface: Surface) -> &'static str {
    if matches!(
        operation,
        OperationKind::ModelList | OperationKind::ModelGet
    ) {
        return "gateway";
    }
    let supported = TransportMode::ALL
        .iter()
        .any(|mode| certification::supports(kind, operation, surface, *mode));
    if !supported {
        "—"
    } else if kind.native_surface() == Some(surface) {
        "native"
    } else {
        "translated"
    }
}
