use axum::{
    Router,
    routing::{get, patch, post},
};
use utoipa::OpenApi;

use crate::{ManagementState, Problem};

pub(crate) mod api_keys;
pub(crate) mod common;
pub(crate) mod providers;
mod routes;

pub fn router() -> Router<ManagementState> {
    Router::new()
        .route(
            "/api/v1/provider-kinds",
            get(providers::list_provider_kinds),
        )
        .route(
            "/api/v1/provider-kinds/{provider_kind}/capabilities",
            get(providers::list_provider_kind_capabilities),
        )
        .route(
            "/api/v1/providers",
            get(providers::list_providers).post(providers::create_provider),
        )
        .route(
            "/api/v1/provider-models",
            get(providers::list_provider_model_inventory),
        )
        .route(
            "/api/v1/providers/{provider_id}",
            get(providers::get_provider).patch(providers::update_provider),
        )
        .route(
            "/api/v1/providers/{provider_id}/activate",
            post(providers::activate_provider),
        )
        .route(
            "/api/v1/providers/{provider_id}/disable",
            post(providers::disable_provider),
        )
        .route(
            "/api/v1/providers/{provider_id}/restore-as-draft",
            post(providers::restore_provider_as_draft),
        )
        .route(
            "/api/v1/providers/{provider_id}/revisions",
            get(providers::list_provider_revisions),
        )
        .route(
            "/api/v1/providers/{provider_id}/revisions/diff",
            get(providers::diff_provider_revisions),
        )
        .route(
            "/api/v1/providers/{provider_id}/revisions/{revision_id}",
            get(providers::get_provider_revision),
        )
        .route(
            "/api/v1/providers/{provider_id}/revisions/{revision_id}/models",
            get(providers::list_provider_revision_models),
        )
        .route(
            "/api/v1/providers/{provider_id}/revisions/{revision_id}/restore-as-draft",
            post(providers::restore_provider_revision),
        )
        .route(
            "/api/v1/providers/{provider_id}/credentials",
            get(providers::list_provider_credentials).post(providers::rotate_provider_credential),
        )
        .route(
            "/api/v1/providers/{provider_id}/credentials/{credential_id}/revoke",
            post(providers::revoke_provider_credential),
        )
        .route(
            "/api/v1/providers/{provider_id}/probe",
            post(providers::probe_provider),
        )
        .route(
            "/api/v1/providers/{provider_id}/discovery",
            post(providers::discover_provider_models),
        )
        .route(
            "/api/v1/providers/{provider_id}/models/{model_id}",
            patch(providers::set_provider_model),
        )
        .route(
            "/api/v1/providers/{provider_id}/models",
            get(providers::list_provider_models),
        )
        .route(
            "/api/v1/providers/{provider_id}/models/{model_id}/certify",
            post(providers::certify_provider_model),
        )
        .route(
            "/api/v1/route-drafts",
            get(routes::list_route_drafts).post(routes::create_route_draft),
        )
        .route(
            "/api/v1/route-drafts/{draft_id}",
            get(routes::get_route_draft)
                .put(routes::replace_route_draft)
                .delete(routes::delete_route_draft),
        )
        .route(
            "/api/v1/route-drafts/{draft_id}/simulate",
            post(routes::simulate_route_draft),
        )
        .route(
            "/api/v1/route-drafts/{draft_id}/validate",
            post(routes::validate_route_draft),
        )
        .route(
            "/api/v1/route-drafts/{draft_id}/activate",
            post(routes::activate_route_draft),
        )
        .route("/api/v1/routes", get(routes::list_routes))
        .route("/api/v1/routes/{route_id}", get(routes::get_route))
        .route(
            "/api/v1/routes/{route_id}/revisions",
            get(routes::list_route_revisions),
        )
        .route(
            "/api/v1/routes/{route_id}/revisions/diff",
            get(routes::diff_route_revisions),
        )
        .route(
            "/api/v1/routes/{route_id}/revisions/{revision_id}",
            get(routes::get_route_revision),
        )
        .route(
            "/api/v1/routes/{route_id}/revisions/{revision_id}/restore-as-draft",
            post(routes::restore_route_revision),
        )
        .route(
            "/api/v1/api-keys",
            get(api_keys::list_api_keys).post(api_keys::create_api_key),
        )
        .route(
            "/api/v1/api-keys/{api_key_id}",
            get(api_keys::get_api_key).patch(api_keys::update_api_key),
        )
        .route(
            "/api/v1/api-keys/{api_key_id}/rotate",
            post(api_keys::rotate_api_key),
        )
        .route(
            "/api/v1/api-keys/{api_key_id}/revoke",
            post(api_keys::revoke_api_key),
        )
}

#[derive(OpenApi)]
#[openapi(
    paths(
        providers::create_provider,
        providers::activate_provider,
        providers::list_provider_kinds,
        providers::list_provider_kind_capabilities,
        providers::list_providers,
        providers::list_provider_model_inventory,
        providers::get_provider,
        providers::list_provider_models,
        providers::update_provider,
        providers::disable_provider,
        providers::restore_provider_as_draft,
        providers::list_provider_revisions,
        providers::get_provider_revision,
        providers::list_provider_revision_models,
        providers::diff_provider_revisions,
        providers::restore_provider_revision,
        providers::list_provider_credentials,
        providers::rotate_provider_credential,
        providers::revoke_provider_credential,
        providers::probe_provider,
        providers::discover_provider_models,
        providers::set_provider_model,
        providers::certify_provider_model,
        routes::create_route_draft,
        routes::validate_route_draft,
        routes::activate_route_draft,
        routes::list_route_drafts,
        routes::get_route_draft,
        routes::replace_route_draft,
        routes::delete_route_draft,
        routes::simulate_route_draft,
        routes::list_routes,
        routes::get_route,
        routes::list_route_revisions,
        routes::get_route_revision,
        routes::diff_route_revisions,
        routes::restore_route_revision,
        api_keys::create_api_key,
        api_keys::revoke_api_key,
        api_keys::list_api_keys,
        api_keys::get_api_key,
        api_keys::update_api_key,
        api_keys::rotate_api_key
    ),
    components(schemas(
        common::PageQuery,
        providers::CreateProviderRequest,
        providers::ProviderResponse,
        providers::ProviderActivationResponse,
        providers::ProviderCapabilityOptionsResponse,
        providers::ProviderAuthCapabilityResponse,
        providers::ProviderFieldCapabilityResponse,
        providers::ProviderKindCapabilityResponse,
        providers::ProviderKindCapabilityListResponse,
        providers::CapabilityResponse,
        providers::ProviderModelResponse,
        providers::ProviderModelListResponse,
        providers::ProviderModelInventoryResponse,
        providers::ProviderModelInventoryListResponse,
        providers::ProviderSummaryResponse,
        providers::ProviderDetailResponse,
        providers::ProviderListResponse,
        providers::ProviderRevisionSummaryResponse,
        providers::ProviderRevisionResponse,
        providers::ProviderRevisionListResponse,
        providers::ProviderRevisionDiffResponse,
        providers::ProviderRevisionRestoreResponse,
        providers::UpdateProviderRequest,
        providers::CredentialResponse,
        providers::CredentialListResponse,
        providers::RotateCredentialRequest,
        providers::ProviderMutationResponse,
        providers::ProbeResponse,
        providers::CapabilityInput,
        providers::DiscoveredModelRequest,
        providers::DiscoverModelsRequest,
        providers::SetModelRequest,
        providers::CapabilityCertificationItemResponse,
        providers::CapabilityCertificationResponse,
        routes::CreateRouteDraftRequest,
        routes::RouteTargetRequest,
        routes::RouteDraftResponse,
        routes::RouteActivationResponse,
        routes::RouteTargetResponse,
        routes::RouteDraftDetailResponse,
        routes::RouteDraftListResponse,
        routes::ReplaceRouteDraftRequest,
        routes::ReplaceRouteTargetRequest,
        routes::SimulateRouteRequest,
        routes::RouteSimulationTargetResponse,
        routes::RouteSimulationResponse,
        routes::RouteDetailResponse,
        routes::RouteListResponse,
        routes::RouteRevisionResponse,
        routes::RouteRevisionListResponse,
        routes::RouteRevisionDiffResponse,
        api_keys::ApiKeyDetailResponse,
        api_keys::ApiKeyListResponse,
        api_keys::UpdateApiKeyRequest,
        api_keys::ApiKeyMutationResponse,
        api_keys::RotateApiKeyResponse,
        api_keys::CreateApiKeyRequest,
        api_keys::CreateApiKeyResponse,
        crate::management_api::common::RuntimeGenerationResponse,
        Problem
    )),
    tags(
        (name = "providers"),
        (name = "routes"),
        (name = "api-keys")
    )
)]
pub struct ConfigurationApiDoc;

#[cfg(test)]
mod tests;
